version: '3'

# Launch: $ docker-compose up -d
services:

  elasticsearch:
    container_name: elasticsearch
    image: es-thavag:${elk_version}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: kibana-thavag:${elk_version}
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200/
    networks:
      - elastic
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    image: logstash-thavag:${elk_version}
    working_dir: /etc/logstash
    ports:
      - 5000:5000/tcp
      - 5000:5000/udp
      - 9600:9600
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/etc/logstash/conf.d:ro
      - ./reports:/etc/logstash:ro
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
      ES_USERNAME: ${ES_USERNAME}
      ES_PASSWORD: ${ES_PASSWORD}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
    networks:
      - elastic

networks:
  elastic:
    {}
